# Generated by Django 4.2.2 on 2023-06-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0002_categorias_product_subcaregorias_delete_masvendidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcaregorias',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=100),
            preserve_default=False,
        ),
    ]
