# Generated by Django 4.2.2 on 2023-06-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0003_subcaregorias_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcaregorias',
            old_name='subcategoria',
            new_name='categoria',
        ),
    ]
