# Generated by Django 4.2.2 on 2023-06-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0004_rename_subcategoria_subcaregorias_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCaregorias',
            new_name='SubCategorias',
        ),
        migrations.AlterModelOptions(
            name='subcategorias',
            options={'verbose_name': 'SubCategorias', 'verbose_name_plural': 'SubCategorias'},
        ),
    ]
