# Generated by Django 4.2.2 on 2023-06-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0005_rename_subcaregorias_subcategorias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategoria',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategoria',
            field=models.ManyToManyField(to='ProductLinkHubApp.subcategorias'),
        ),
    ]
