# Generated by Django 4.2.2 on 2023-06-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0006_remove_product_subcategoria_product_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subcategorias',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
