# Generated by Django 4.2.2 on 2023-06-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0007_categorias_disponible_product_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorias',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
