# Generated by Django 4.2.2 on 2023-07-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0008_subcategorias_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategoria',
            field=models.ManyToManyField(blank=True, null=True, to='ProductLinkHubApp.subcategorias'),
        ),
    ]
