# Generated by Django 4.2.2 on 2023-07-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0010_alter_product_product_alter_product_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.TextField(),
        ),
    ]
