# Generated by Django 4.2.2 on 2023-07-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0012_alter_subcategorias_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ProductoLinkHubApp')),
            ],
        ),
    ]
