# Generated by Django 4.2.2 on 2023-07-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0013_imagenfondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenfondo',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
