# Generated by Django 4.2.2 on 2023-07-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0015_alter_imagenfondo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenfondo',
            name='imagen',
            field=models.ImageField(upload_to='ProductLinkHubApp/media/imagenes_fondo'),
        ),
    ]
