# Generated by Django 4.2.2 on 2023-08-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0016_alter_imagenfondo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoriaSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'SubCategoriaSeccion',
                'verbose_name_plural': 'SubCategoriaSeccions',
            },
        ),
    ]
