# Generated by Django 4.2.2 on 2023-08-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0017_subcategoriaseccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoriaseccion',
            name='url_texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
