# Generated by Django 4.2.2 on 2023-08-10 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0020_productsubcategoriaseccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubcategoriaseccion',
            options={'verbose_name': 'ProductSubCategoriaSeccion', 'verbose_name_plural': 'ProductSubCategoriaSeccions'},
        ),
    ]
