# Generated by Django 4.2.2 on 2023-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductLinkHubApp', '0021_alter_productsubcategoriaseccion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenfondo',
            name='enlace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
